web:
  build: .
  links:
    - elasticsearch
    - mysql
  ports:
    - 80:80
  volumes:
    - /var/www/SugarPro-Full-7.5.2.1:/var/www/sugarcrm
elasticsearch:
  image: elasticsearch
mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=sugarcrm
    - MYSQL_DATABASE=sugarcrm
    - MYSQL_USER=sugarcrm
    - MYSQL_PASSWORD=sugarcrm
